exception.internal.error=Podczas przetwarzania ¿¹dania wyst¹pi³ b³¹d.